package com.imemalta.api.gourmetSnApp.dtos;

public enum ApiErrorCode {
    NOT_LOGGED_IN,
    CONSTRAIN_VIOLATION,
    USER_NOT_FOUND,
    DUPLICATE_EMAIL,
    DUPLICATE_USERNAME,
    CHANGE_OWN_ROLES,
    DELETE_OWN_USER,
    CHANGE_OWN_ACCOUNT_STATE,
    CHANGE_OWN_ACTIVE_DATES,
    ACCOUNT_ALREADY_ACTIVE,
    INVALID_ACCOUNT_STATE_CHANGE,
    PASSWORD_NOT_SECURE,
    INVALID_PASSWORD,
    TOKEN_NOT_FOUND,
    INVALID_TOKEN_TYPE,
    EXPIRED_TOKEN,
    NOT_FOUND,
    NO_SUBSCRIPTION,
    UNPAID_SUBSCRIPTION,
    INDEX_ALREADY_IN_USE,
    STRIPE_ERROR
}
